config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources  :articles
	
	#	get "/articles" index
	#	post "/articles" create
	#	delete "/articles/:id" destroy
	#	get "/articles/:id" show
	#	get "/articles/:new" new 
	#	get "/articles/:id/edit" edit
	#	path "/articles/:id" update
	#	put "/articles/:id" update
	

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: {minimum: 20}
	before_save :set_visits_count

	def update_visits_count
		#self.save if self.visits_count.nil?
	 	self.update(visits_count: self.visits_count + 1)	
	end

	private
	def set_visits_count
	  self.visits_count ||= 0	
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show,:index]
  before_action :set_article, except: [:index, :new, :create]
  # Get /articles
  def index
  	# Todos los registros
  	@articles = Article.all
  end
  # Get /articles/:id
  def show
    @article.update_visits_count
  end
  # Get /articles/new
  def new
  	@article = Article.new
  end

  def edit
  
  end

  # Post /articles
  def create
  		# insert into
  	@article = current_user.articles.new(article_params)

  	if @article.save
  		redirect_to @article 
  	else
  		render :new
  	end
  end

  def destroy
  	# delete from articles
  	
  	@article.destroy # destroy elimina el objeto de la base de datos
  	redirect_to articles_path  
  end

  def update
  	# update
  	# @article.update_attributes({titulo: 'nuevo titulo'})
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  	
  private
  
  def set_article
    @article = Article.find(params[:id])
  end

  def validate_user
    redirect_to new_user_session_path, notice: "Es necesario iniciar sesión"
  end

  def article_params
  	params.require(:article).permit(:title,:body)	
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |message| %>
	<div class="be-red white top-space">
	  * <%= message %>		
	</div>
	<%end%>

	<div class="field">
	  <%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
	</div>
	<div class="field">
	<%= f.text_area :body, placeholder: "Escribe aqui el articulo", style:"height:250px;", class:"form-control" %>	
	</div>
	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white" %>
	<%end%>	

app/views/articles/edit.html.erb
<div style="width: 80%; margin: 0 auto;">
  <h1>Editar Articulo</h1>
	<%= render "form" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<h1> <%= link_to article.title, article %></h1>
<div>
	<%=	article.body %> - <%= link_to "Eliminar", article, method: :delete, class:"red" %>
<div>
<%end %>	

app/views/articles/new.html.erb
<div style="width: 80%; margin: 0 auto;">
  <h1>Crear Articulo</h1>
  	<%= render "form" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>	
<% unless @article.user.nil? %>
<p>
	Escrito por: <%= @article.user.email  %>
</p>

<% end %>
<p>
	Visitas: <%= @article.visits_count  %>
</p>
<div>
	<%= @article.body %>
</div>

<div>
	
	<%= link_to "Editar", edit_article_path(@article), class:"red" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render "partials/navegation" %>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

   


    <%= yield %>
    
  </body>
</html>

app/views/partials/_navegation.html.erb
<header>
  <nav class="be-red white large-padding">
    <div class="row">
      <div class="col-sm">
        <%= link_to "Inicio", root_path %>
      </div>
      <% if user_signed_in? %>
      <div class="col-sm">
        <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
      </div>
      <%else%>
      <div class="col-sm">
        <%= link_to "Iniciar sesion", new_user_session_path %>
      </div>
      <div class="col-sm">
        <%= link_to "Crear Cuenta", new_user_registration_path %>
      </div>
    </div>
    <% end%>    
  </nav>
</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<div class="text-center">
<h1> Bienvenido <%= current_user.email %></h1>
</div>
<% end %>